version: '3'
volumes:
  database:
  ldap-data:
  ldap-conf:
  jboss:
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=haraka
      - POSTGRES_USER=haraka
      - POSTGRES_DB=haraka
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'
  testdb:
      image: postgres:alpine
      environment:
        - POSTGRES_PASSWORD=haraka
        - POSTGRES_USER=haraka
        - POSTGRES_DB=haraka
  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_PASSWORD=haraka
      - SLAPD_DOMAIN=com.terarion
    volumes:
      - 'ldap-data:/var/lib/ldap'
      - 'ldap-conf:/etc/ldap'
    ports:
      - '389:389'
  jboss:
    image: jboss/wildfly
    command: /opt/jboss/wildfly/bin/standalone.sh -bmanagement 0.0.0.0
    links:
      - db
      - ldap
    depends_on:
      - db
      - ldap
    ports:
      - "8081:8080"
      - "9991:9990"
    volumes:
      - 'jboss:/opt/jboss/wildfly/standalone/configuration'
      - './build/deployment:/opt/jboss/wildfly/standalone/deployments'
