version: '3'
volumes:
  database:
  ldap-data:
  ldap-conf:
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=haraka
      - POSTGRES_USER=haraka
      - POSTGRES_DB=haraka
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'
  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_PASSWORD=haraka
      - SLAPD_DOMAIN=com.terarion
    volumes:
      - 'ldap-data:/var/lib/ldap'
      - 'ldap-conf:/etc/ldap'
    ports:
      - '389:389'
